### ISSUE TITLE
Missing libs

### ISSUE THREAD

**Issue by koosy-koo** [yangxue0827/R-DFPN_FPN_Tensorflow#1]
Hi, 

I very appreciate your efforts for sharing the nice implementation. In this repository, I could not find some libs including configs, fast_rcnn, rpn ..., which are necessary to run your code. 

Do you have a plan to update this repository as a complete one?

**Comment by yangxue0827** [comment]
This code is not updated for some reason, you can see another project （https://github.com/yangxue0827/R2CNN_FPN_Tensorflow）.

**Comment by koosy-koo** [comment]
Thanks for your quick answer. I tried R2CNN_FPN, and it was great as well. Many thanks :+1:

**Comment by yangxue0827** [comment]
The code of R-DFPN_FPN_Tensorflow has been completely uploaded.
