### ISSUE TITLE
I get some trouble in compile

### ISSUE THREAD

**Issue by RicardoYoung96** [yangxue0827/R-DFPN_FPN_Tensorflow#22]
Hi, I had get some trouble  when tried to use setup.py to compile 'rbbox_overlaps_kernels.cu'.
It raised :
"Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 47, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME"
What should I do ?

**Comment by RicardoY97** [comment]
I also tried the setup_new.py to compile, which I find from net ,but it also filed.

**Comment by RicardoYoung96** [comment]
I also tried the setup_new.py to compile, which I find from net ,but it also filed.
[setup.zip](https://github.com/yangxue0827/R-DFPN_FPN_Tensorflow/files/3235138/setup.zip)
